### ISSUE TITLE
Move Notebooks to a different repo

### ISSUE THREAD

**Issue by brmather** [underworldcode/quagmire#11]
Still need to decide whether to include a stripped back user manual for Quagmire, but all workflow stuff should be moved out of the man repository.

I still like the idea of using Quagmire to install the documentation.
```python
quagmire.documentation.install_documentation(path="./Quagmire-Notebooks")
```
Perhaps a good solution is for this function to clone the examples/community repo to the install location, and download all the data to run the examples from CloudStor.

**Comment by lmoresi** [comment]
https://github.com/underworld-community/quagmire-examples-and-workflows - no fix as yet for allowing the documentation module to grab this repo ...
