### ISSUE TITLE
Pixmesh Octopants issue

### ISSUE THREAD

**Issue by lmoresi** [underworldcode/quagmire#12]
Pixmesh example (Pixmesh Octopants) - some missing functionality in Pixmesh ?

(https://github.com/underworld-community/quagmire-examples-and-workflows/blob/master/Notebooks/IdealisedExamples/PixMeshOctoPants.ipynb)

```sh
~/+Codes/Python/quagmire/quagmire/topomesh/topomesh.py in _build_down_neighbour_arrays(self, nearest)
    189         nheightn = nheight.copy()
    190         # nheightn[~self.near_neighbour_mask] += self.height.max()
--> 191         nheightn[~self.near_neighbour_mask] += self._heightVariable.data.max()
    192         nheightnidx = np.argsort(nheightn, axis=1)
    193 

AttributeError: 'SurfaceProcessMeshClass' object has no attribute 'near_neighbour_mask'
```

**Comment by brmather** [comment]
This has been fixed in 24f2ec5ce751a12bf572e423d85b04d03e61efc8 and the notebook updated to be compatible with the function interface.
