### ISSUE TITLE
Setting downhill neighbours

### ISSUE THREAD

**Issue by brmather** [underworldcode/quagmire#17]
In `SurfaceProcessMesh`, the context manager to update the topography rebuilds the downhill matrix and integrates the upstream area, whereas the downhill_neighbours setter just rebuilds the downhill matrix. This is because the property is defined only on the TopoMesh class while the context manager is overridden on the SurfMesh class. I'm not sure if this is intended?

Also it would be good to have the option to set the downhill neighbours from the context manager, e.g.
```python
class Surfmesh_Height_Update_Manager(object):
    """Manage when changes to the height information trigger a rebuild
    of the topomesh matrices and other internal data.
    """

    def __init__(inner_self, downhill_neighbours=downhill_neighbours):
        inner_self._surfmesh = surfmesh
        inner_self._topovar = topographyVariable
        inner_self._downhill_neighbours = int(downhill_neighbours)
        return

    def __enter__(inner_self):
        # unlock
        inner_self._topovar.unlock()
        inner_self._surfmesh._downhill_neighbours = inner_self._downhill_neighbours
        return

    def __exit__(inner_self, *args):
        inner_self._surfmesh._update_height()
        inner_self._surfmesh._update_height_for_surface_flows()
        inner_self._topovar.lock()
        return
```

**Comment by lmoresi** [comment]
I think you are right to flag this, @brmather. What it probably indicates is that we have one too many layers of inheritance. The topomesh would do most of the job and we no longer really need all the surface process mesh hanger-on functions as we have largely switched out that functionality to replace it with the generic function capability.  At some point, we should start to view much of what is in the spmesh class as being about workflow rather than about some inherent property of the mesh and drop it. 

Qn - should the upstream / uphill area be in the topomesh in the first place ?

**Comment by brmather** [comment]
We could probably collapse most of what's in SurfaceProcessMesh into TopoMesh i.e. all the landscape processing stuff like swamp fill, backfill, outflow identification. The landscape evolution stuff in SurfMesh is mostly redundant code that is superseded by the equation_systems submodule which implements the functions interface.

While we're at it, perhaps we don't even need a distinction between FlatMesh and TopoMesh...? None of the data structures in TopoMesh are built until a topography is initialised. I suggest we keep the two classes, so we don't slowly go insane with merge conflicts, but expose just TopoMesh to the user in `__init__.py` - or call it something cool like `QuagMesh`!

**Comment by lmoresi** [comment]
I agree - a quagmesh object that combines topo and the remaining, useful spmesh functionality.

However, I am not looking forward to the name change.

L

Prof Louis Moresi

louis.moresi@anu.edu.au

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>

On 8 May 2020, 12:06 PM +1000, Ben Mather <notifications@github.com>, wrote:

We could probably collapse most of what's in SurfaceProcessMesh into TopoMesh i.e. all the landscape processing stuff like swamp fill, backfill, outflow identification. The landscape evolution stuff in SurfMesh is mostly redundant code that is superseded by the equation_systems submodule which implements the functions interface.

While we're at it, perhaps we don't even need a distinction between FlatMesh and TopoMesh...? None of the data structures in TopoMesh are built until a topography is initialised. I suggest we keep the two classes, so we don't slowly go insane with merge conflicts, but expose just TopoMesh to the user in __init__.py - or call it something cool like QuagMesh!

**Comment by brmather** [comment]
It should be fine... just a recursive grep operation to replace instances of FlatMesh, TopoMesh, SurfaceProcessMesh with QuagMesh. One mesh object to rule them all...
