### ISSUE TITLE
Conda-based testing

### ISSUE THREAD

**Issue by lmoresi** [underworldcode/quagmire#25]
The updated petsc etc (#10) has broken the old conda-based build and test workflow. Should be simple to update but does need to be done.

**Comment by rbeucher** [comment]
I am working on it

**Comment by brmather** [comment]
The tests are still failing on the test stage, and from the error messages it looks like conda must be installing some version of quagmire without `QuagMesh`. I think we should have separate actions for testing with pytest and building a Quagmire binary to upload to the cloud. The former should run on every push, the latter on every push to the master branch.

**Comment by lmoresi** [comment]
Agreed - the tests can’t be based on an uploaded version or there will be a race condition.
Binaries really should update on a release rather than a push.


Prof Louis Moresi

louis.moresi@anu.edu.au

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>

On 28 May 2020, 4:17 PM +1000, Ben Mather <notifications@github.com>, wrote:

The tests are still failing on the test stage, and from the error messages it looks like conda must be installing some version of quagmire without QuagMesh. I think we should have separate actions for testing with pytest and building a Quagmire binary to upload to the cloud. The former should run on every push, the latter on every push to the master branch.

**Comment by rbeucher** [comment]
All right, my bad, it was still getting quagmire from my branch.
I have made the changes.

**Comment by brmather** [comment]
I can't seem to install petsc binaries with a fresh conda install (using a [miniconda3 docker container](https://hub.docker.com/r/continuumio/miniconda3)).

```
conda install -c underworldcode petsc
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
```

**Comment by lmoresi** [comment]
Prof Louis Moresi

louis.moresi@anu.edu.au

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>

On 29 May 2020, 2:13 PM +1000, Ben Mather <notifications@github.com>, wrote:

I can't seem to install petsc binaries with a fresh conda install (using a miniconda3 docker container<https://hub.docker.com/r/continuumio/miniconda3>).

conda install -c underworldcode petsc
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

**Comment by lmoresi** [comment]
Unclear why that should be - a completely clean environment ?

Prof Louis Moresi

louis.moresi@anu.edu.au

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>

On 29 May 2020, 2:13 PM +1000, Ben Mather <notifications@github.com>, wrote:

I can't seem to install petsc binaries with a fresh conda install (using a miniconda3 docker container<https://hub.docker.com/r/continuumio/miniconda3>).

conda install -c underworldcode petsc
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

**Comment by brmather** [comment]
That's right. More output:

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package _libgcc_mutex conflicts for:
petsc -> libgcc-ng[version='>=7.5.0'] -> _libgcc_mutex=[build=main]
python=3.7 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]

Package libstdcxx-ng conflicts for:
petsc -> metis[version='>=5.1.0,<5.2.0a0'] -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
petsc -> libstdcxx-ng[version='>=7.5.0']

Package libgcc-ng conflicts for:
petsc -> libgcc-ng[version='>=7.5.0']
petsc -> metis[version='>=5.1.0,<5.2.0a0'] -> libgcc-ng[version='>=7.2.0|>=7.3.0']
```

**Comment by rbeucher** [comment]
Yeah... I can't either. Well I can install petsc fine. But I struggle with quagmire. !!!!!

**Comment by rbeucher** [comment]
I think I need to build it with more flexible settings.

**Comment by lmoresi** [comment]
It would probably work just fine if you removed the hdf5 options
On 29 May 2020, 2:33 PM +1000, Romain Beucher <notifications@github.com>, wrote:

I think I need to build it with more flexible settings.

**Comment by brmather** [comment]
What I don't understand is that installing the conda-forge petsc pulls in hdf5, but petsc doesn't compile against it.

**Comment by rbeucher** [comment]
Looking at it now. QUAG-3 QUAG-4

**Comment by rbeucher** [comment]
OK comes from h5py that does not have a build with HDF5 1.10.6.
They seem to have some issues with windows. We can build our own h5py in our channel for now.

**Comment by brmather** [comment]
Fingers crossed PR https://github.com/conda-forge/h5py-feedstock/pull/72 is merged soon!

**Comment by brmather** [comment]
#28 has been merged into dev. Thanks @rbeucher for all your hard work getting conda to work with Quagmire! I'm closing this issue...
