### ISSUE TITLE
loading into a locked mesh variable. 

### ISSUE THREAD

**Issue by lmoresi** [underworldcode/quagmire#32]
```python
mesh.topography.load("global_OC_8.4_topography.h5")
```
should fail because the topography variable is locked (because it should be used within a context manager). The following is not allowed without the context manager

```python
mesh.topography.data = 0.0
```

**Comment by brmather** [comment]
Loading mesh variables is parallel safe, but you're right - it should only be allowed if the mesh variable is unlocked.
