### ISSUE TITLE
Extended neighbour cloud

### ISSUE THREAD

**Issue by brmather** [underworldcode/quagmire#7]
I don't think I understood this at the time... here are you including the two closest neighbours outside the immediate node neighbours? Sort of a limited extended-neighbours search?

https://github.com/underworldcode/quagmire/blob/f6c6f5b821def61199d7112f255bb371c9160bf6/quagmire/mesh/trimesh.py#L352-L353

**Comment by lmoresi** [comment]
Not sure why this is done this way. This functionality should probably be deprecated as it was added to avoid having to implement the flood-filling algorithms in full.

**Comment by brmather** [comment]
This array masks points in the `near_neighbour_mask`, which is currently used in:

- `low_points_swamp_fill` in `SurfMesh`
- `_build_down_neighbour_arrays` in `TopoMesh`

So we can't remove it just yet before testing if it breaks everything...

**Comment by lmoresi** [comment]
I see that ... I am wondering about that 2. Perhaps we have +1 for the local node which will appear in the k-d tree array and 1 for the indexing / slicing ? Or something like that. 

The main issue is that we don't have a good way to identify the natural neighbours using k-d-tree and it is extra work / storage to keep both sets of neighbours. This could use a bit of an audit.

**Comment by lmoresi** [comment]
Let's ensure this is not used for the adjacency calculations.

**Comment by brmather** [comment]
I've pushed a re-jigged `construct_neighbour_cloud` method to the "natural_neighbour" branch for testing.

https://github.com/underworldcode/quagmire/blob/5bd81e8d734eff54e9bfd5f989df62891f479c59/quagmire/mesh/trimesh.py#L451-L498

It's horrendously inefficient. Any more than 10000 points per processor then you'd better brew a cup of tea.
